version: 1
disable_existing_loggers: False


formatters:
  default:
    format: '#%(levelname)-8s %(name)s:%(funcName)s - %(message)s'

  main_formatter:
    format: '#%(levelname)s - %(filename)s - %(message)s'


handlers:
  default:
    class: logging.StreamHandler
    formatter: default

  main_handler:
    class: logging.StreamHandler
    formatter: main_formatter

loggers:
  __main__:
    level: INFO
    handlers: [main_handler]
    propagate: False

  root:
    level: WARNING
    handlers: [default]
